# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xci
# IP: The module: 'fdma_mig_ddr_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xci
# IP: The module: 'fdma_mig_ddr_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
