# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Project/xk265/extif/extif.srcs/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0.xci
# IP: The module: 'fdma_mig_ddr_auto_us_df_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_auto_us_df_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_auto_us_df_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Project/xk265/extif/extif.srcs/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0.xci
# IP: The module: 'fdma_mig_ddr_auto_us_df_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_auto_us_df_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fdma_mig_ddr_auto_us_df_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
