set_property PACKAGE_PIN AD23 [get_ports pclk_i]
set_property PACKAGE_PIN AF24 [get_ports de_i]
set_property PACKAGE_PIN AE21 [get_ports hsync_i]
set_property PACKAGE_PIN AB21 [get_ports sii_rst_n]
set_property PACKAGE_PIN AC23 [get_ports sii_scl]
set_property PACKAGE_PIN AC22 [get_ports sii_sda]
set_property PACKAGE_PIN AD21 [get_ports vsync_i]
set_property PACKAGE_PIN AF23 [get_ports {rgb_i[0]}]
set_property PACKAGE_PIN AE23 [get_ports {rgb_i[1]}]
set_property PACKAGE_PIN AD24 [get_ports {rgb_i[2]}]
set_property PACKAGE_PIN AC24 [get_ports {rgb_i[3]}]
set_property PACKAGE_PIN AA24 [get_ports {rgb_i[4]}]
set_property PACKAGE_PIN AB24 [get_ports {rgb_i[5]}]
set_property PACKAGE_PIN Y22 [get_ports {rgb_i[6]}]
set_property PACKAGE_PIN Y23 [get_ports {rgb_i[7]}]
set_property PACKAGE_PIN AA22 [get_ports {rgb_i[8]}]
set_property PACKAGE_PIN AA23 [get_ports {rgb_i[9]}]
set_property PACKAGE_PIN AJ24 [get_ports {rgb_i[10]}]
set_property PACKAGE_PIN AJ23 [get_ports {rgb_i[11]}]
set_property PACKAGE_PIN AJ21 [get_ports {rgb_i[12]}]
set_property PACKAGE_PIN AK21 [get_ports {rgb_i[13]}]
set_property PACKAGE_PIN AK23 [get_ports {rgb_i[14]}]
set_property PACKAGE_PIN AK22 [get_ports {rgb_i[15]}]
set_property PACKAGE_PIN AH24 [get_ports {rgb_i[16]}]
set_property PACKAGE_PIN AH23 [get_ports {rgb_i[17]}]
set_property PACKAGE_PIN AJ20 [get_ports {rgb_i[18]}]
set_property PACKAGE_PIN AK20 [get_ports {rgb_i[19]}]
set_property PACKAGE_PIN AH21 [get_ports {rgb_i[20]}]
set_property PACKAGE_PIN AG21 [get_ports {rgb_i[21]}]
set_property PACKAGE_PIN AG20 [get_ports {rgb_i[22]}]
set_property PACKAGE_PIN AF20 [get_ports {rgb_i[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports pclk_i]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_i]
set_property IOSTANDARD LVCMOS33 [get_ports de_i]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_i]
set_property IOSTANDARD LVCMOS33 [get_ports sii_scl]
set_property IOSTANDARD LVCMOS33 [get_ports sii_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sii_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[*]}]

set_property PULLUP true [get_ports sii_sda]
set_property PULLUP true [get_ports sii_scl]

connect_debug_port u_ila_1/probe0 [get_nets [list vhes_core_top/hdmi2yuv_top/sii_rst_n_OBUF]]
connect_debug_port u_ila_1/probe1 [get_nets [list vhes_core_top/hdmi2yuv_top/sii_cfg_done_reg]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100M]
