set_property PACKAGE_PIN AD23 [get_ports pclk_i]
set_property PACKAGE_PIN AF24 [get_ports de_i]
set_property PACKAGE_PIN AE21 [get_ports hsync_i]
set_property PACKAGE_PIN AD21 [get_ports vsync_i]
set_property PACKAGE_PIN AF23 [get_ports {rgb_i[0]}]
set_property PACKAGE_PIN AE23 [get_ports {rgb_i[1]}]
set_property PACKAGE_PIN AD24 [get_ports {rgb_i[2]}]
set_property PACKAGE_PIN AC24 [get_ports {rgb_i[3]}]
set_property PACKAGE_PIN AA24 [get_ports {rgb_i[4]}]
set_property PACKAGE_PIN AB24 [get_ports {rgb_i[5]}]
set_property PACKAGE_PIN Y22 [get_ports {rgb_i[6]}]
set_property PACKAGE_PIN Y23 [get_ports {rgb_i[7]}]
set_property PACKAGE_PIN AA22 [get_ports {rgb_i[8]}]
set_property PACKAGE_PIN AA23 [get_ports {rgb_i[9]}]
set_property PACKAGE_PIN AJ24 [get_ports {rgb_i[10]}]
set_property PACKAGE_PIN AJ23 [get_ports {rgb_i[11]}]
set_property PACKAGE_PIN AJ21 [get_ports {rgb_i[12]}]
set_property PACKAGE_PIN AK21 [get_ports {rgb_i[13]}]
set_property PACKAGE_PIN AK23 [get_ports {rgb_i[14]}]
set_property PACKAGE_PIN AK22 [get_ports {rgb_i[15]}]
set_property PACKAGE_PIN AH24 [get_ports {rgb_i[16]}]
set_property PACKAGE_PIN AH23 [get_ports {rgb_i[17]}]
set_property PACKAGE_PIN AJ20 [get_ports {rgb_i[18]}]
set_property PACKAGE_PIN AK20 [get_ports {rgb_i[19]}]
set_property PACKAGE_PIN AH21 [get_ports {rgb_i[20]}]
set_property PACKAGE_PIN AG21 [get_ports {rgb_i[21]}]
set_property PACKAGE_PIN AG20 [get_ports {rgb_i[22]}]
set_property PACKAGE_PIN AF20 [get_ports {rgb_i[23]}]
set_property PACKAGE_PIN AB21 [get_ports sii_rst_n]
set_property PACKAGE_PIN AC23 [get_ports sii_scl]
set_property PACKAGE_PIN AC22 [get_ports sii_sda]

set_property PACKAGE_PIN AJ16 [get_ports sys_init_done_o]
set_property PACKAGE_PIN AK16 [get_ports bs_overflow_n_o]
set_property PACKAGE_PIN AE16 [get_ports skip_frame_flag_n_o]

set_property PULLUP true [get_ports sii_sda]
set_property PULLUP true [get_ports sii_scl]

set_property IOSTANDARD LVCMOS33 [get_ports pclk_i]
set_property IOSTANDARD LVCMOS33 [get_ports de_i]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_i]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_i]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports sii_scl]
set_property IOSTANDARD LVCMOS33 [get_ports sii_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sii_sda]

set_property IOSTANDARD LVCMOS33 [get_ports sys_init_done_o]
set_property IOSTANDARD LVCMOS33 [get_ports bs_overflow_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports skip_frame_flag_n_o]

create_clock -period 6.734 -name pclk_i -waveform {0.000 3.367} [get_ports pclk_i]
set_input_delay -clock [get_clocks pclk_i] -min -add_delay 1.010 [get_ports {rgb_i[*]}]
set_input_delay -clock [get_clocks pclk_i] -max -add_delay 2.500 [get_ports {rgb_i[*]}]
set_input_delay -clock [get_clocks pclk_i] -min -add_delay 1.010 [get_ports de_i]
set_input_delay -clock [get_clocks pclk_i] -max -add_delay 2.500 [get_ports de_i]
set_input_delay -clock [get_clocks pclk_i] -min -add_delay 1.010 [get_ports hsync_i]
set_input_delay -clock [get_clocks pclk_i] -max -add_delay 2.500 [get_ports hsync_i]
set_input_delay -clock [get_clocks pclk_i] -min -add_delay 1.010 [get_ports vsync_i]
set_input_delay -clock [get_clocks pclk_i] -max -add_delay 2.500 [get_ports vsync_i]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pclk_i_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {vhes_core_top/hdmi2yuv_top/rgb2yuv/de[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {vhes_core_top/hdmi2yuv_top/rgb2yuv/hsync[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/y_recorded]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/yuv_de]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/uv_recorded]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/uv_col_recorded]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/uv_row_recorded]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list vhes_core_top/hdmi2yuv_top/rgb2yuv/clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list vhes_core_top/vsp_top/vsync_i_IBUF]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list vhes_core_top/extif_top/fmd_wrapper/fmd_i/mig_7series_0/u_fmd_mig_7series_0_0_mig/u_ddr3_infrastructure/u_bufg_clkdiv0_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 11 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {vhes_core_top/pixel_buffer_rd_cnt[0]} {vhes_core_top/pixel_buffer_rd_cnt[1]} {vhes_core_top/pixel_buffer_rd_cnt[2]} {vhes_core_top/pixel_buffer_rd_cnt[3]} {vhes_core_top/pixel_buffer_rd_cnt[4]} {vhes_core_top/pixel_buffer_rd_cnt[5]} {vhes_core_top/pixel_buffer_rd_cnt[6]} {vhes_core_top/pixel_buffer_rd_cnt[7]} {vhes_core_top/pixel_buffer_rd_cnt[8]} {vhes_core_top/pixel_buffer_rd_cnt[9]} {vhes_core_top/pixel_buffer_rd_cnt[10]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {vhes_core_top/vhes_core_rst_done_i[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 24 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[0]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[1]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[2]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[3]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[4]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[5]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[6]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[7]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[8]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[9]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[10]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[11]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[12]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[13]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[14]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[15]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[16]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[17]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[18]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[19]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[20]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[21]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[22]} {vhes_core_top/hdmi2yuv_top/rgb2yuv/rgb_i_IBUF[23]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 2 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {vhes_core_top/hevc_encode_system_ctrl/state[0]} {vhes_core_top/hevc_encode_system_ctrl/state[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 8 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {vhes_core_top/bs_data[0]} {vhes_core_top/bs_data[1]} {vhes_core_top/bs_data[2]} {vhes_core_top/bs_data[3]} {vhes_core_top/bs_data[4]} {vhes_core_top/bs_data[5]} {vhes_core_top/bs_data[6]} {vhes_core_top/bs_data[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {vhes_core_top/vsp_top/vhes_core_rst_done_i[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 8 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {vhes_core_top/vsp_top/frame_sn_i_reg[0]} {vhes_core_top/vsp_top/frame_sn_i_reg[1]} {vhes_core_top/vsp_top/frame_sn_i_reg[2]} {vhes_core_top/vsp_top/frame_sn_i_reg[3]} {vhes_core_top/vsp_top/frame_sn_i_reg[4]} {vhes_core_top/vsp_top/frame_sn_i_reg[5]} {vhes_core_top/vsp_top/frame_sn_i_reg[6]} {vhes_core_top/vsp_top/frame_sn_i_reg[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/current_read_frame_serial_number]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/fdma_busy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/FDMA_S_i_fdma_rbusy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/FDMA_S_i_fdma_wareq]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/FDMA_S_i_fdma_wbusy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/hevc_enc_busy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/hevc_sys_start]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/is_fifo_write]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/pixel_buffer_rd_en]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list vhes_core_top/hevc_encode_system_ctrl/pixel_type]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list vhes_core_top/vsp_top/bs_fifo_wr_rst_busy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list vhes_core_top/vsp_top/vsps_index]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list sys_wrapper/system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {vhes_core_top/vhes_core_rst_n_o[0]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {vhes_core_top/hevc_encode_system_ctrl/vhes_core_rst_n_o[0]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list {vhes_core_top/vsp_top/axis_transform_start_o[0]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list vhes_core_top/vsp_top/bs_fifo_rd_rst_busy]]
create_debug_core u_ila_3 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_3]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_3]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_3]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_3]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_3]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
set_property port_width 1 [get_debug_ports u_ila_3/clk]
connect_debug_port u_ila_3/clk [get_nets [list vsp_top/clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
set_property port_width 32 [get_debug_ports u_ila_3/probe0]
connect_debug_port u_ila_3/probe0 [get_nets [list {vhes_core_top/vsp_top/hevc_bs_data[0]} {vhes_core_top/vsp_top/hevc_bs_data[1]} {vhes_core_top/vsp_top/hevc_bs_data[2]} {vhes_core_top/vsp_top/hevc_bs_data[3]} {vhes_core_top/vsp_top/hevc_bs_data[4]} {vhes_core_top/vsp_top/hevc_bs_data[5]} {vhes_core_top/vsp_top/hevc_bs_data[6]} {vhes_core_top/vsp_top/hevc_bs_data[7]} {vhes_core_top/vsp_top/hevc_bs_data[8]} {vhes_core_top/vsp_top/hevc_bs_data[9]} {vhes_core_top/vsp_top/hevc_bs_data[10]} {vhes_core_top/vsp_top/hevc_bs_data[11]} {vhes_core_top/vsp_top/hevc_bs_data[12]} {vhes_core_top/vsp_top/hevc_bs_data[13]} {vhes_core_top/vsp_top/hevc_bs_data[14]} {vhes_core_top/vsp_top/hevc_bs_data[15]} {vhes_core_top/vsp_top/hevc_bs_data[16]} {vhes_core_top/vsp_top/hevc_bs_data[17]} {vhes_core_top/vsp_top/hevc_bs_data[18]} {vhes_core_top/vsp_top/hevc_bs_data[19]} {vhes_core_top/vsp_top/hevc_bs_data[20]} {vhes_core_top/vsp_top/hevc_bs_data[21]} {vhes_core_top/vsp_top/hevc_bs_data[22]} {vhes_core_top/vsp_top/hevc_bs_data[23]} {vhes_core_top/vsp_top/hevc_bs_data[24]} {vhes_core_top/vsp_top/hevc_bs_data[25]} {vhes_core_top/vsp_top/hevc_bs_data[26]} {vhes_core_top/vsp_top/hevc_bs_data[27]} {vhes_core_top/vsp_top/hevc_bs_data[28]} {vhes_core_top/vsp_top/hevc_bs_data[29]} {vhes_core_top/vsp_top/hevc_bs_data[30]} {vhes_core_top/vsp_top/hevc_bs_data[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets vsp_top/clk]
