# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_xbar_0/hevc_encoder_system_xbar_0.xci
# IP: The module: 'hevc_encoder_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_xbar_0/hevc_encoder_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_xbar_0/hevc_encoder_system_xbar_0.xci
# IP: The module: 'hevc_encoder_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_xbar_0/hevc_encoder_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
