set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_uiFDMA_0_0/fdma_mig_ddr_uiFDMA_0_0/fdma_mig_ddr_uiFDMA_0_0_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_uiFDMA_0_0/fdma_mig_ddr_uiFDMA_0_0/fdma_mig_ddr_uiFDMA_0_0_in_context.xdc id:1 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/uiFDMA_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0_in_context.xdc id:2 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/s00_regslice} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_in_context.xdc id:3 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/auto_us_df} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_in_context.xdc id:4 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/proc_sys_reset_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1_in_context.xdc id:5 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0_in_context.xdc id:6 order:EARLY scoped_inst:exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo/pixel_y_fifo_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo/pixel_y_fifo_in_context.xdc id:7 order:EARLY scoped_inst:exif_top/video_in_buffer/pixel_y_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo/pixel_y_fifo_in_context.xdc rfile:../../../../../hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo/pixel_y_fifo_in_context.xdc id:8 order:EARLY scoped_inst:exif_top/video_in_buffer/pixel_uv_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/constrs_1/new/hevc_encoder_system.xdc rfile:../../../../../hevc_encoder_system.srcs/constrs_1/new/hevc_encoder_system.xdc id:9} [current_design]
set_property SRC_FILE_INFO {cfile:E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:10} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/uiFDMA_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/s00_regslice/aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/s00_regslice]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/auto_us_df/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/auto_us_df]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/proc_sys_reset_0/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/proc_sys_reset_0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0/ui_clk [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0/ui_clk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[10]}]
set_property src_info {type:SCOPED_XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[10]}]
set_property src_info {type:SCOPED_XDC file:5 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[11]}]
set_property src_info {type:SCOPED_XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[11]}]
set_property src_info {type:SCOPED_XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[12]}]
set_property src_info {type:SCOPED_XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[12]}]
set_property src_info {type:SCOPED_XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[13]}]
set_property src_info {type:SCOPED_XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[13]}]
set_property src_info {type:SCOPED_XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[14]}]
set_property src_info {type:SCOPED_XDC file:5 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[14]}]
set_property src_info {type:SCOPED_XDC file:5 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[4]}]
set_property src_info {type:SCOPED_XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[4]}]
set_property src_info {type:SCOPED_XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[5]}]
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[5]}]
set_property src_info {type:SCOPED_XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[6]}]
set_property src_info {type:SCOPED_XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[6]}]
set_property src_info {type:SCOPED_XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[7]}]
set_property src_info {type:SCOPED_XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[7]}]
set_property src_info {type:SCOPED_XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[8]}]
set_property src_info {type:SCOPED_XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[8]}]
set_property src_info {type:SCOPED_XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[9]}]
set_property src_info {type:SCOPED_XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_addr[9]}]
set_property src_info {type:SCOPED_XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_ba[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR3_o_cas_n]
set_property src_info {type:SCOPED_XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR3_o_cas_n]
set_property src_info {type:SCOPED_XDC file:5 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_cke[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_cke[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dm[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[10]}]
set_property src_info {type:SCOPED_XDC file:5 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[10]}]
set_property src_info {type:SCOPED_XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[11]}]
set_property src_info {type:SCOPED_XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[11]}]
set_property src_info {type:SCOPED_XDC file:5 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[12]}]
set_property src_info {type:SCOPED_XDC file:5 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[12]}]
set_property src_info {type:SCOPED_XDC file:5 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[13]}]
set_property src_info {type:SCOPED_XDC file:5 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[13]}]
set_property src_info {type:SCOPED_XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[14]}]
set_property src_info {type:SCOPED_XDC file:5 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[14]}]
set_property src_info {type:SCOPED_XDC file:5 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[15]}]
set_property src_info {type:SCOPED_XDC file:5 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[15]}]
set_property src_info {type:SCOPED_XDC file:5 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[16]}]
set_property src_info {type:SCOPED_XDC file:5 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[16]}]
set_property src_info {type:SCOPED_XDC file:5 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[17]}]
set_property src_info {type:SCOPED_XDC file:5 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[17]}]
set_property src_info {type:SCOPED_XDC file:5 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[18]}]
set_property src_info {type:SCOPED_XDC file:5 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[18]}]
set_property src_info {type:SCOPED_XDC file:5 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[19]}]
set_property src_info {type:SCOPED_XDC file:5 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[19]}]
set_property src_info {type:SCOPED_XDC file:5 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[20]}]
set_property src_info {type:SCOPED_XDC file:5 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[20]}]
set_property src_info {type:SCOPED_XDC file:5 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[21]}]
set_property src_info {type:SCOPED_XDC file:5 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[21]}]
set_property src_info {type:SCOPED_XDC file:5 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[22]}]
set_property src_info {type:SCOPED_XDC file:5 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[22]}]
set_property src_info {type:SCOPED_XDC file:5 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[23]}]
set_property src_info {type:SCOPED_XDC file:5 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[23]}]
set_property src_info {type:SCOPED_XDC file:5 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[24]}]
set_property src_info {type:SCOPED_XDC file:5 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[24]}]
set_property src_info {type:SCOPED_XDC file:5 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[25]}]
set_property src_info {type:SCOPED_XDC file:5 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[25]}]
set_property src_info {type:SCOPED_XDC file:5 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[26]}]
set_property src_info {type:SCOPED_XDC file:5 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[26]}]
set_property src_info {type:SCOPED_XDC file:5 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[27]}]
set_property src_info {type:SCOPED_XDC file:5 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[27]}]
set_property src_info {type:SCOPED_XDC file:5 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[28]}]
set_property src_info {type:SCOPED_XDC file:5 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[28]}]
set_property src_info {type:SCOPED_XDC file:5 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[29]}]
set_property src_info {type:SCOPED_XDC file:5 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[29]}]
set_property src_info {type:SCOPED_XDC file:5 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[30]}]
set_property src_info {type:SCOPED_XDC file:5 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[30]}]
set_property src_info {type:SCOPED_XDC file:5 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[31]}]
set_property src_info {type:SCOPED_XDC file:5 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[31]}]
set_property src_info {type:SCOPED_XDC file:5 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[4]}]
set_property src_info {type:SCOPED_XDC file:5 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[4]}]
set_property src_info {type:SCOPED_XDC file:5 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[5]}]
set_property src_info {type:SCOPED_XDC file:5 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[5]}]
set_property src_info {type:SCOPED_XDC file:5 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[6]}]
set_property src_info {type:SCOPED_XDC file:5 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[6]}]
set_property src_info {type:SCOPED_XDC file:5 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[7]}]
set_property src_info {type:SCOPED_XDC file:5 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[7]}]
set_property src_info {type:SCOPED_XDC file:5 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[8]}]
set_property src_info {type:SCOPED_XDC file:5 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[8]}]
set_property src_info {type:SCOPED_XDC file:5 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[9]}]
set_property src_info {type:SCOPED_XDC file:5 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dq[9]}]
set_property src_info {type:SCOPED_XDC file:5 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:5 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:5 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:5 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {DDR3_o_odt[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {DDR3_o_odt[0]}]
set_property src_info {type:SCOPED_XDC file:5 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR3_o_ras_n]
set_property src_info {type:SCOPED_XDC file:5 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR3_o_ras_n]
set_property src_info {type:SCOPED_XDC file:5 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR3_o_reset_n]
set_property src_info {type:SCOPED_XDC file:5 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR3_o_reset_n]
set_property src_info {type:SCOPED_XDC file:5 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports DDR3_o_we_n]
set_property src_info {type:SCOPED_XDC file:5 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports DDR3_o_we_n]
set_property src_info {type:SCOPED_XDC file:5 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0/sys_clk_i]
set_property src_info {type:SCOPED_XDC file:5 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100M_i [get_ports clk_100M_i]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0/clk_200M -source [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0/clk_in1] -edges {1 2 3} -edge_shift {0.000 -2.500 -5.000} [get_pins exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0/clk_200M]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk_100M_i]
set_property src_info {type:SCOPED_XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk_100M_i]
set_property src_info {type:SCOPED_XDC file:6 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins exif_top/video_in_buffer/pixel_y_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins exif_top/video_in_buffer/pixel_y_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/video_in_buffer/pixel_y_fifo]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins exif_top/video_in_buffer/pixel_uv_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins exif_top/video_in_buffer/pixel_uv_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells exif_top/video_in_buffer/pixel_uv_fifo]
set_property src_info {type:XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[23]}]
set_property src_info {type:XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[22]}]
set_property src_info {type:XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[21]}]
set_property src_info {type:XDC file:9 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[20]}]
set_property src_info {type:XDC file:9 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[19]}]
set_property src_info {type:XDC file:9 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[18]}]
set_property src_info {type:XDC file:9 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[17]}]
set_property src_info {type:XDC file:9 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[16]}]
set_property src_info {type:XDC file:9 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[15]}]
set_property src_info {type:XDC file:9 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[14]}]
set_property src_info {type:XDC file:9 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[13]}]
set_property src_info {type:XDC file:9 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[12]}]
set_property src_info {type:XDC file:9 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[11]}]
set_property src_info {type:XDC file:9 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[10]}]
set_property src_info {type:XDC file:9 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[9]}]
set_property src_info {type:XDC file:9 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[8]}]
set_property src_info {type:XDC file:9 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[7]}]
set_property src_info {type:XDC file:9 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[6]}]
set_property src_info {type:XDC file:9 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[5]}]
set_property src_info {type:XDC file:9 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[4]}]
set_property src_info {type:XDC file:9 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[3]}]
set_property src_info {type:XDC file:9 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[2]}]
set_property src_info {type:XDC file:9 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[1]}]
set_property src_info {type:XDC file:9 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i[0]}]
set_property src_info {type:XDC file:9 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports adv_pen_o]
set_property src_info {type:XDC file:9 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports adv_rst_o]
set_property src_info {type:XDC file:9 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports adv_scl]
set_property src_info {type:XDC file:9 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports adv_sda]
set_property src_info {type:XDC file:9 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports de_i]
set_property src_info {type:XDC file:9 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pclk_i]
set_property src_info {type:XDC file:9 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n_i]
set_property src_info {type:XDC file:9 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports adv_sda]
set_property src_info {type:XDC file:9 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports adv_scl]
set_property src_info {type:XDC file:9 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports adv_sda]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/uiFDMA_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/s00_regslice]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0/s00_couplers/auto_us_df]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/proc_sys_reset_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/mig_7series_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/fdma_mig_ddr_wrapper/fdma_mig_ddr_i/clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/video_in_buffer/pixel_uv_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells exif_top/video_in_buffer/pixel_y_fifo]
