# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z035ffg676-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl
    e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ipshared/ec67/hdl
    e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ipshared/4e49
  } {
      D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl
    e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ipshared/ec67/hdl
    e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ipshared/4e49
  } {
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_uiFDMA_0_0_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_s00_regslice_0_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_auto_us_df_0_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_proc_sys_reset_0_0_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_mig_7series_0_1_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/fdma_mig_ddr_clk_wiz_0_0_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/pixel_fifo_stub.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/DC_Plannar.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/IinP_flag_gen.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/addr_ctl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_delay.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_level0.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_level1.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/buf_ram_1p_128x64.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/buf_ram_1p_64x64.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina_lut.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina_tools.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_binmix.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_binsort.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bitpack.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/cabac_ram_sp_64x16.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_rlps4.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_rlps4_1bin.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_amplitude_of_coeff.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_coeff.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_coeff_last_sig_xy.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_cu.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_intra.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_intra_luma.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_mv.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_mvd.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_sao_offset.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_sig_coeff_ctx.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_tu.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext_t.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext_tt.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow_1bin.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow_refine.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_urange4.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_urange4_full.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/chroma_qp.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/coe_addr_trans.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/compare.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/control.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/counter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl0.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl1.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl2.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl3.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/data_merge.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_bs.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_cbf_ram_sp_64x16.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_chroma_filter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_clip3_str.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_filter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_lut_beta.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_lut_tc.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_mv.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_mv_ram_sp_512x20.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_mv_ram_sp_64x20.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_normal_filter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_pu_edge.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_qp.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_qp_ram_sp_64x20.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_strong_filter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_tu_edge.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_tupu_ram_sp_64x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_controller.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_datapath.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/dct_top_2d.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_core.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_data_pipeline.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/exif/exif_top.v
      e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/hdl/fdma_mig_ddr_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/fetch8x8.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_cur_chroma.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_cur_luma.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_db.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_ram_1p_128x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_ram_2p_64x208.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_ref_chroma.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_ref_luma.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_rf_1p_128x512.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_rf_1p_64x256.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_buf_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_cost.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator_8pel.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator_8x8.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ip_half_ver.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ip_quarter_ver.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_mv_buffer.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_mv_candidate_prepare.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fme_mv_ram_dp_64x20.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_pred.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_satd_8x8.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_satd_gen.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_skip.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/fme_top_buf.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/gxgy.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/hdmi2rgb.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/hdmi2yuv_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hevc_encoder_system_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/hevc_md_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_addressing.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_cost_store.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_dat_array.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_mv_dump.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ime_mv_ram_sp_64x13.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_partition_decision.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_partition_decision_engine.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_sad_array.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/ime_top_buf.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_transfer.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_ver_mem.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_buf_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_pred.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_ref.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_filter.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_ip4x4.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_ip_1p.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mc_mv_ram_sp_512x20.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_tq.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/md_fetch.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/md_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/mem_bilo_db.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mem_lipo_1p_128x64x4.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mem_lipo_1p_64x64x4.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mod.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/mode_write.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux0.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux1.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux2.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux3.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux32_1.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_can_mv_addr.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_getBits.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/offset_shift.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/pe.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/pe_i.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/pipo.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_buffer.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_ctrl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/posi_md_ram_sp_64x6.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_memory_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_partition_decision.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_prediction.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_rate_estimation.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_reference.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost_engine.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost_transpose.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/posi_top_buf.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_transfer.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/prei_md_ram_sp_85x6.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/prei_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/prei_top_buf.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/q_iq.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/qp_lambda_table.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/quan.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/ram_1p.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/ram_dp.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_1024x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_1536x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_240x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_256x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_384x32.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_128x64.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x128.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x512.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x64.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_64x23.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_tp_be_32x64.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/rate_control.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_in_ctl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level0.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level0_cal.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level1.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level1_cal.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level2.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level2_cal.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level3.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_out_ctl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_cef.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_cef_rot.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_mvd_rot.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_pre.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_rec.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_rec_rot.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_wrapper.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/rf_1p.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/rgb2yuv.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/row_ctl.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_add_offset.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_bo_predecision.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_cal_offset.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_mode.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_statistic.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_sum_diff.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_type_decision.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/sram_sp_be_behave.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/sram_tp_be_behave.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/tq_ram_sp_32x16.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/tq_top.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/transform_mtr.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/ui7611reg.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/uicfg7611.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/uii2c.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/exif/video_in_buffer.v
      E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hevc_encoder_system_top.v
      e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/synth/fdma_mig_ddr.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/realtime/hevc_encoder_system_top_synth.xdc
    rt::sdcChecksum
    set rt::top hevc_encoder_system_top
    rt::set_parameter incrementalOnCache "E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    set_param edifin.funnel true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/.Xil/Vivado-127692-JingDevice/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
