
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_AXIS_TRANSMIT_START_DEVICE_ID,
		XPAR_GPIO_AXIS_TRANSMIT_START_BASEADDR,
		XPAR_GPIO_AXIS_TRANSMIT_START_INTERRUPT_PRESENT,
		XPAR_GPIO_AXIS_TRANSMIT_START_IS_DUAL
	},
	{
		XPAR_GPIO_PL_RST_N_DEVICE_ID,
		XPAR_GPIO_PL_RST_N_BASEADDR,
		XPAR_GPIO_PL_RST_N_INTERRUPT_PRESENT,
		XPAR_GPIO_PL_RST_N_IS_DUAL
	},
	{
		XPAR_GPIO_SII_RST_N_DEVICE_ID,
		XPAR_GPIO_SII_RST_N_BASEADDR,
		XPAR_GPIO_SII_RST_N_INTERRUPT_PRESENT,
		XPAR_GPIO_SII_RST_N_IS_DUAL
	},
	{
		XPAR_GPIO_VHES_CORE_RST_DONE_DEVICE_ID,
		XPAR_GPIO_VHES_CORE_RST_DONE_BASEADDR,
		XPAR_GPIO_VHES_CORE_RST_DONE_INTERRUPT_PRESENT,
		XPAR_GPIO_VHES_CORE_RST_DONE_IS_DUAL
	}
};


