# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hevc_encoder_system.xdc

# Block Designs: bd/fdma_mig_ddr/fdma_mig_ddr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr || ORIG_REF_NAME==fdma_mig_ddr} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_uiFDMA_0_0/fdma_mig_ddr_uiFDMA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_uiFDMA_0_0 || ORIG_REF_NAME==fdma_mig_ddr_uiFDMA_0_0} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_axi_interconnect_0_0/fdma_mig_ddr_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_axi_interconnect_0_0 || ORIG_REF_NAME==fdma_mig_ddr_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_proc_sys_reset_0_0 || ORIG_REF_NAME==fdma_mig_ddr_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_mig_7series_0_1 || ORIG_REF_NAME==fdma_mig_ddr_mig_7series_0_1} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_clk_wiz_0_0 || ORIG_REF_NAME==fdma_mig_ddr_clk_wiz_0_0} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_s00_regslice_0 || ORIG_REF_NAME==fdma_mig_ddr_s00_regslice_0} -quiet] -quiet

# IP: bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fdma_mig_ddr_auto_us_df_0 || ORIG_REF_NAME==fdma_mig_ddr_auto_us_df_0} -quiet] -quiet

# IP: ip/pixel_fifo/pixel_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pixel_fifo || ORIG_REF_NAME==pixel_fifo} -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/fdma_mig_ddr_ooc.xdc
