# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.runs/synth_1/hevc_encoder_system_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.cache/wt [current_project]
set_property parent.project_path E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/Project/ZynqLearning/code/IP/ip_repo
  e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.ip_user_files/uisrc
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/enc_defines.v
set_property file_type "Verilog Header" [get_files E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/enc_defines.v]
read_verilog -library xil_defaultlib {
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/DC_Plannar.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/IinP_flag_gen.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/addr_ctl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_delay.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_level0.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/be_level1.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/buf_ram_1p_128x64.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/buf_ram_1p_64x64.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina_lut.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bina_tools.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_binmix.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_binsort.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_bitpack.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/cabac_ram_sp_64x16.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_rlps4.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_rlps4_1bin.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_amplitude_of_coeff.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_coeff.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_coeff_last_sig_xy.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_cu.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_intra.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_intra_luma.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_mv.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_mvd.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_sao_offset.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_sig_coeff_ctx.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_se_prepare_tu.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext_t.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ucontext_tt.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow_1bin.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_ulow_refine.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_urange4.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/cabac_urange4_full.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/chroma_qp.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/coe_addr_trans.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/compare.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/control.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/counter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl0.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl1.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl2.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/ctl3.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/data_merge.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_bs.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_cbf_ram_sp_64x16.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_chroma_filter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_clip3_str.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_filter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_lut_beta.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_lut_tc.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_mv.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_mv_ram_sp_512x20.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_mv_ram_sp_64x20.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_normal_filter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_pu_edge.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_qp.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_qp_ram_sp_64x20.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_strong_filter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/db_tu_edge.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/db_tupu_ram_sp_64x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_controller.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_datapath.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/dbsao_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/dct_top_2d.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_core.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_data_pipeline.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/enc_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/exif/exif_top.v
  e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/hdl/fdma_mig_ddr_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/fetch8x8.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_cur_chroma.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_cur_luma.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_db.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_ram_1p_128x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_ram_2p_64x208.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_ref_chroma.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_ref_luma.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_rf_1p_128x512.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fetch_rf_1p_64x256.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/fetch_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_buf_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_cost.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator_8pel.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_interpolator_8x8.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ip_half_ver.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_ip_quarter_ver.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_mv_buffer.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_mv_candidate_prepare.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/fme_mv_ram_dp_64x20.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_pred.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_satd_8x8.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_satd_gen.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_skip.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/fme_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/fme_top_buf.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/gxgy.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/hdmi2rgb.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/hdmi2yuv_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hevc_encoder_system_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/hevc_md_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_addressing.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_cost_store.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_dat_array.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_mv_dump.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ime_mv_ram_sp_64x13.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_partition_decision.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_partition_decision_engine.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_sad_array.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/ime_top_buf.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_transfer.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/ime/ime_ver_mem.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_buf_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_pred.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_ref.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_intra/intra_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_filter.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_ip4x4.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_ip_1p.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_chroma_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mc_mv_ram_sp_512x20.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mc_tq.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/md_fetch.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/md_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fetch/mem_bilo_db.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mem_lipo_1p_128x64x4.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/mem_lipo_1p_64x64x4.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mod.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/mode_write.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux0.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux1.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux2.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux3.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/mux32_1.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_can_mv_addr.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_getBits.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_mc/mvd_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/offset_shift.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/pe.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/pe_i.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/cabac/pipo.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_buffer.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_ctrl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/posi_md_ram_sp_64x6.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_memory_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_partition_decision.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_prediction.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_rate_estimation.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_reference.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost_engine.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_satd_cost_transpose.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/posi_top_buf.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/posi/posi_transfer.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/prei_md_ram_sp_85x6.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/prei_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/top/prei_top_buf.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/q_iq.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/fme/qp_lambda_table.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/quan.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/ram_1p.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/ram_dp.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_1024x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_1536x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_240x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_256x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_384x32.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_128x64.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x128.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x512.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_192x64.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_sp_be_64x23.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/ram_tp_be_32x64.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/prei/rate_control.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_in_ctl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level0.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level0_cal.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level1.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level1_cal.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level2.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level2_cal.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_level3.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/re_out_ctl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_cef.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_cef_rot.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_mvd_rot.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_pre.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_rec.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_rec_rot.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_wrapper/rec_buf_wrapper.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/rf_1p.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/rgb2yuv.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/row_ctl.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_add_offset.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_bo_predecision.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_cal_offset.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_mode.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_statistic.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_sum_diff.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/db/sao_type_decision.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/sram_sp_be_behave.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/lib/behave/mem/sram_tp_be_behave.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/mem/tq_ram_sp_32x16.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/tq_top.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/enc_core/rtl/rec/rec_tq/transform_mtr.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/ui7611reg.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/uicfg7611.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hdmi2yuv/uii2c.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/exif/video_in_buffer.v
  E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/new/hevc_encoder_system_top.v
}
add_files E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/fdma_mig_ddr/fdma_mig_ddr.bd
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_proc_sys_reset_0_0/fdma_mig_ddr_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1/user_design/constraints/fdma_mig_ddr_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_mig_7series_0_1/fdma_mig_ddr_mig_7series_0_1/user_design/constraints/fdma_mig_ddr_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_clk_wiz_0_0/fdma_mig_ddr_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_s00_regslice_0/fdma_mig_ddr_s00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/ip/fdma_mig_ddr_auto_us_df_0/fdma_mig_ddr_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/fdma_mig_ddr/fdma_mig_ddr_ooc.xdc]

read_ip -quiet E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/ip/pixel_fifo/pixel_fifo.xci
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/ip/pixel_fifo/pixel_fifo_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/constrs_1/new/hevc_encoder_system.xdc
set_property used_in_implementation false [get_files E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/constrs_1/new/hevc_encoder_system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/utils_1/imports/synth_1/hdmi2rgb.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top hevc_encoder_system_top -part xc7z035ffg676-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hevc_encoder_system_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hevc_encoder_system_top_utilization_synth.rpt -pb hevc_encoder_system_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
