# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1.xci
# IP: The module: 'hevc_encoder_system_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.srcs/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1.xci
# IP: The module: 'hevc_encoder_system_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/hevc_encoder_system/hevc_encoder_system.gen/sources_1/bd/hevc_encoder_system/ip/hevc_encoder_system_proc_sys_reset_0_1/hevc_encoder_system_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hevc_encoder_system_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
