# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/xk265/extif/extif.srcs/sources_1/ip/test_fifo/test_fifo.xci
# IP: The module: 'test_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Project/xk265/extif/extif.srcs/sources_1/ip/test_fifo/test_fifo.xci
# IP: The module: 'test_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/xk265/extif/extif.gen/sources_1/ip/test_fifo/test_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
