######################################################################
#
# File name : hevc_enc_core_top_tb_simulate.do
# Created on: Wed May 03 00:10:10 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.hevc_enc_core_top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {hevc_enc_core_top_tb_wave.do}

view wave
view structure
view signals

do {hevc_enc_core_top_tb.udo}

run 1000ns
