######################################################################
#
# File name : hevc_enc_core_top_tb_wave.do
# Created on: Tue May 02 19:37:54 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
