######################################################################
#
# File name : xk265_top_tb_wave.do
# Created on: Sun Apr 30 23:49:00 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
