######################################################################
#
# File name : data_merge_tb_simulate.do
# Created on: Fri Apr 21 22:46:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.data_merge_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {data_merge_tb_wave.do}

view wave
view structure
view signals

do {data_merge_tb.udo}

run 1000ns
