######################################################################
#
# File name : data_merge_tb_wave.do
# Created on: Fri Apr 21 22:46:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
