######################################################################
#
# File name : data_merge_tb_compile.do
# Created on: Fri Apr 21 22:46:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  "+incdir+../../../../extif.gen/sources_1/bd/fdma_mig_ddr/ipshared/ec67/hdl" \
"../../../../extif.srcs/sources_1/new/data_merge.v" \
"../../../../extif.srcs/sim_1/new/data_merge_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

