######################################################################
#
# File name : tb_enc_top_simulate.do
# Created on: Sun Apr 23 21:43:51 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_enc_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_enc_top_wave.do}

view wave
view structure
view signals

do {tb_enc_top.udo}

run 1000ns
