######################################################################
#
# File name : tb_enc_top_wave.do
# Created on: Sun Apr 23 18:15:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
