onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_enc_top/bs_val_o
add wave -noupdate /tb_enc_top/bs_dat_o
add wave -noupdate /tb_enc_top/rstn
add wave -noupdate /tb_enc_top/sys_rc_roi_y
add wave -noupdate /tb_enc_top/sys_start
add wave -noupdate /tb_enc_top/sys_type
add wave -noupdate /tb_enc_top/sys_all_x
add wave -noupdate /tb_enc_top/sys_all_y
add wave -noupdate /tb_enc_top/sys_init_qp
add wave -noupdate /tb_enc_top/sys_done
add wave -noupdate /tb_enc_top/sys_IinP_ena
add wave -noupdate /tb_enc_top/sys_dbsao_ena
add wave -noupdate /tb_enc_top/sys_posi4x4bit
add wave -noupdate /tb_enc_top/skip_cost_thresh_08
add wave -noupdate /tb_enc_top/skip_cost_thresh_16
add wave -noupdate /tb_enc_top/skip_cost_thresh_32
add wave -noupdate /tb_enc_top/skip_cost_thresh_64
add wave -noupdate /tb_enc_top/sys_rc_bitnum_i
add wave -noupdate /tb_enc_top/sys_rc_k
add wave -noupdate /tb_enc_top/sys_rc_roi_height
add wave -noupdate /tb_enc_top/sys_rc_roi_width
add wave -noupdate /tb_enc_top/sys_rc_roi_x
add wave -noupdate /tb_enc_top/sys_rc_roi_enable
add wave -noupdate /tb_enc_top/sys_rc_L1_frame_byte
add wave -noupdate /tb_enc_top/sys_rc_L2_frame_byte
add wave -noupdate /tb_enc_top/sys_rc_lcu_en
add wave -noupdate /tb_enc_top/sys_rc_max_qp
add wave -noupdate /tb_enc_top/sys_rc_min_qp
add wave -noupdate /tb_enc_top/sys_rc_delta_qp
add wave -noupdate /tb_enc_top/cmd_num_i
add wave -noupdate /tb_enc_top/cmd_dat_i
add wave -noupdate /tb_enc_top/extif_start_o
add wave -noupdate /tb_enc_top/extif_done_i
add wave -noupdate /tb_enc_top/extif_mode_o
add wave -noupdate /tb_enc_top/extif_x_o
add wave -noupdate /tb_enc_top/extif_y_o
add wave -noupdate /tb_enc_top/extif_width_o
add wave -noupdate /tb_enc_top/extif_height_o
add wave -noupdate /tb_enc_top/extif_wren_i
add wave -noupdate /tb_enc_top/clk
add wave -noupdate /tb_enc_top/extif_rden_i
add wave -noupdate /tb_enc_top/extif_data_o
add wave -noupdate /tb_enc_top/extif_data_i
add wave -noupdate /tb_enc_top/ext_height
add wave -noupdate /tb_enc_top/ext_width
add wave -noupdate /tb_enc_top/ext_addr
add wave -noupdate /tb_enc_top/fp_cfg
add wave -noupdate /tb_enc_top/fp_ori
add wave -noupdate /tb_enc_top/fp_rec
add wave -noupdate /tb_enc_top/fp_ref
add wave -noupdate /tb_enc_top/fp_init
add wave -noupdate /tb_enc_top/fp_check_bs
add wave -noupdate /tb_enc_top/frame_num
add wave -noupdate /tb_enc_top/pxl_cnt
add wave -noupdate /tb_enc_top/pxl_adr
add wave -noupdate /tb_enc_top/ext_tmp_yuv
add wave -noupdate /tb_enc_top/bs_byte_cnt
add wave -noupdate /tb_enc_top/check_bs
add wave -noupdate /tb_enc_top/center_x_r
add wave -noupdate /tb_enc_top/center_y_r
add wave -noupdate /tb_enc_top/length_x_r
add wave -noupdate /tb_enc_top/length_y_r
add wave -noupdate /tb_enc_top/slope_r
add wave -noupdate /tb_enc_top/downsample_r
add wave -noupdate /tb_enc_top/partition_r
add wave -noupdate /tb_enc_top/use_feedback_r
add wave -noupdate /tb_enc_top/ime_cfg
add wave -noupdate /tb_enc_top/fp_ime_cfg
add wave -noupdate /tb_enc_top/ime_cfg_dat
add wave -noupdate /tb_enc_top/rc_cfg
add wave -noupdate /tb_enc_top/fp_reg_k
add wave -noupdate /tb_enc_top/fp_frame_qp
add wave -noupdate /glbl/GSR
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {360099962 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 251
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {360078653 ps} {360103611 ps}
