######################################################################
#
# File name : rgb2yuv_tb_simulate.do
# Created on: Thu Apr 13 20:25:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.rgb2yuv_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {rgb2yuv_tb_wave.do}

view wave
view structure
view signals

do {rgb2yuv_tb.udo}

run 1000ns
