######################################################################
#
# File name : rgb2yuv_tb_wave.do
# Created on: Thu Apr 13 18:56:42 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
