######################################################################
#
# File name : rgb2yuv_tb_compile.do
# Created on: Thu Apr 13 20:25:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../hevc_encoder_system.srcs/sources_1/rgb2yuv/rgb2yuv.v" \
"../../../../hevc_encoder_system.srcs/sim_1/new/rgb2yuv_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

