######################################################################
#
# File name : tb_enc_top_wave.do
# Created on: Mon Apr 24 20:08:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
